// apps/director/frontend/packages/layout/src/vue/AppShell.vue
<template>
  <div class="app-shell" :style="shellStyle">
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, provide } from 'vue';
import { AppShellConfig, defaultAppShellConfig, createLayoutStructure } from '../core/app-shell';

interface Props {
  config?: AppShellConfig;
}

const props = withDefaults(defineProps<Props>(), {
  config: () => defaultAppShellConfig,
});

const sidebarCollapsed = ref(props.config.sidebar.defaultCollapsed);

const toggleSidebar = () => {
  sidebarCollapsed.value = !sidebarCollapsed.value;
};

const layoutStructure = createLayoutStructure(props.config);

const shellStyle = computed(() => layoutStructure.appShell);

provide('appShell', {
  sidebarCollapsed,
  toggleSidebar,
  config: props.config,
});
</script>

<style scoped>
.app-shell {
  width: 100vw;
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: var(--bg-app, #050505);
}
</style>

// packages/layout/src/react/AppShell.tsx
import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { AppShellConfig, defaultAppShellConfig, createLayoutStructure } from '../core/app-shell';

interface AppShellContextValue {
  sidebarCollapsed: boolean;
  toggleSidebar: () => void;
  config: AppShellConfig;
}

const AppShellContext = createContext<AppShellContextValue | null>(null);

export function useAppShell() {
  const context = useContext(AppShellContext);
  if (!context) {
    throw new Error('useAppShell must be used within an AppShell provider');
  }
  return context;
}

interface AppShellProps {
  children: ReactNode;
  config?: AppShellConfig;
  className?: string;
}

export function AppShell({ children, config = defaultAppShellConfig, className = '' }: AppShellProps) {
  const [sidebarCollapsed, setSidebarCollapsed] = useState(config.sidebar.defaultCollapsed);

  const toggleSidebar = useCallback(() => {
    setSidebarCollapsed(prev => !prev);
  }, []);

  const layoutStructure = createLayoutStructure(config);

  return (
    <AppShellContext.Provider value={{ sidebarCollapsed, toggleSidebar, config }}>
      <div
        className={`app-shell ${className}`}
        style={layoutStructure.appShell as any}
      >
        {children}
      </div>
    </AppShellContext.Provider>
  );
}
