// packages/layout/src/react/ContentArea.tsx
import React, { ReactNode } from 'react';
import { ContentAreaConfig, defaultContentAreaConfig, createContentAreaStructure } from '../core/content-area';

interface ContentAreaProps {
  children: ReactNode;
  config?: ContentAreaConfig;
  className?: string;
}

export function ContentArea({
  children,
  config = defaultContentAreaConfig,
  className = '',
}: ContentAreaProps) {
  const contentStructure = createContentAreaStructure(config);

  return (
    <main
      className={`content-area ${className}`}
      style={contentStructure.container}
    >
      <div style={contentStructure.inner}>
        {children}
      </div>
    </main>
  );
}

// packages/layout/src/vue/ContentArea.vue
<template>
  <main class="content-area" :style="containerStyle">
    <div :style="innerStyle">
      <slot></slot>
    </div>
  </main>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { ContentAreaConfig, defaultContentAreaConfig, createContentAreaStructure } from '../core/content-area';

interface Props {
  config?: ContentAreaConfig;
}

const props = withDefaults(defineProps<Props>(), {
  config: () => defaultContentAreaConfig,
});

const contentStructure = createContentAreaStructure(props.config);

const containerStyle = computed(() => contentStructure.container);
const innerStyle = computed(() => contentStructure.inner);
</script>

<style scoped>
.content-area {
  flex: 1;
  position: relative;
  display: flex;
  flex-direction: column;
  background: var(--bg-app, #050505);
  width: 100%;
  height: 100%;
  overflow: hidden;
}
</style>
